name: NoWorld
main: com.c45y.NoWorld.NoWorld
version: 0.1
load: startup
permissions:
    World.user:
        description: A player
        default: true
    World.op:
        description: A admin type player
        default: op
commands:
  get:
    description: A general purpose command for commanding things!
    permission: World.user
    usage: |
           /get: param
           